@startuml
HttpServletBean -> HttpServletBean: init()
HttpServletBean -> FrameworkServlet: initServletBean()

FrameworkServlet -> FrameworkServlet: initWebApplicationContext()
FrameworkServlet -> DispatcherServlet: initFrameworkServlet()
@enduml
